# Generated by Django 2.2.13 on 2022-03-24 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('nome_prenot', models.CharField(max_length=153)),
                ('carrello', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prod', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note', models.TextField(max_length=240)),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
    ]
