# Generated by Django 2.2.13 on 2022-03-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
