# Generated by Django 3.2 on 2022-04-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0005_auto_20220325_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinazione',
            name='carrello',
        ),
        migrations.AddField(
            model_name='ordinazione',
            name='totale',
            field=models.FloatField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ombrellone',
            name='note',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ordinazione',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='note',
            field=models.TextField(blank=True, max_length=240),
        ),
    ]
