# Generated by Django 3.2 on 2022-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0006_auto_20220406_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='totale',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
