# Generated by Django 3.2 on 2022-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0007_alter_ordinazione_totale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinazione',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
