# Generated by Django 3.2 on 2022-04-06 17:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0008_alter_ordinazione_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinazione',
            name='ordine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default='dasd', size=30),
            preserve_default=False,
        ),
    ]
