# Generated by Django 3.2 on 2022-04-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0009_ordinazione_ordine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinazione',
            name='ordine',
        ),
    ]
