# Generated by Django 3.2 on 2022-04-06 17:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ordinazioni', '0010_remove_ordinazione_ordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinazione',
            name='carrello',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=django.utils.timezone.now, size=30),
            preserve_default=False,
        ),
    ]
